compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1088783
  - 1092429
  - 1095136
  - 1089718
  - 1092461
  - ts-custom-error (deprecation)
  - text-encoding (deprecation)
  - popper.js (deprecation)
  - mini-create-react-context (deprecation)
  - uuid (deprecation)
  - '@npmcli/move-file (deprecation)'
  - core-js (deprecation)
  - '@material-ui/core (deprecation)'
  - '@material-ui/styles (deprecation)'
  - '@material-ui/system (deprecation)'
  - '@ensdomains/ens (deprecation)'
  - '@ensdomains/resolver (deprecation)'
  - 'testrpc (deprecation)'

  # Dependencies brought in by @truffle/decoder that are deprecated:
  - 'cids (deprecation)' # via @ensdomains/content-hash
  - 'multibase (deprecation)' # via cids
  - 'multicodec (deprecation)' # via cids

  # MetaMask owned repositories brought in by other MetaMask dependencies that
  # can be resolved by updating the versions throughout the dependency tree
  - 'eth-sig-util (deprecation)' # via @metamask/eth-ledger-bridge-keyring
  - '@metamask/controller-utils (deprecation)' # via @metamask/phishing-controller
  - 'safe-event-emitter (deprecation)' # via eth-block-tracker and others

  # @metamask-institutional relies upon crypto which is deprecated
  - 'crypto (deprecation)'

  # @metamask/providers uses webextension-polyfill-ts which has been moved to
  # @types/webextension-polyfill
  - 'webextension-polyfill-ts (deprecation)'

  # Imported in @trezor/blockchain-link@npm:2.1.8, but not actually depended on
  # by MetaMask
  - 'ripple-lib (deprecation)'

  # Brought in by ethereumjs-utils, which is used in the extension and in many
  # other dependencies. At the time of this exclusion, the extension has three
  # old versions of ethereumjs-utils which should be upgraded to
  # @ethereumjs/utils throughout our owned repositories. However even doing
  # that may be insufficient due to dependencies we do not own still relying
  # upon old versions of ethereumjs-utils.
  - 'ethereum-cryptography (deprecation)'

  # Currently in use for the network list drag and drop functionality.
  # Maintenance has stopped and the project will be archived in 2025.
  - 'react-beautiful-dnd (deprecation)'
  # New package name format for new versions: @ethereumjs/wallet.
  - 'ethereumjs-wallet (deprecation)'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
